/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NullProgrammers_08;

import NullProgrammers_08.Models.Imodels;
import NullProgrammers_08.Models.AbsenView;
import NullProgrammers_08.Models.KelasModel;
import NullProgrammers_08.Models.DetailAbsensiModel;
import NullProgrammers_08.Models.HeaderAbsensiModel;
import NullProgrammers_08.Models.UsersModel;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
//import javaapplication2.Entities.Absensidetail;
//import javaapplication2.Entities.Absensiheader;
//import javaapplication2.Entities.Users;
import NullProgrammers_08.Libs.AbsensiTableModel;
import NullProgrammers_08.Libs.AbsensiTableRenderer;
import NullProgrammers_08.Libs.sqlLib;
import NullProgrammers_08.Libs.utilLib;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author DRONE003
 */

public class AbsensiForm extends javax.swing.JFrame {

    /**
     * Creates new form AbsensiForm
     */
    public static UsersModel user;
    public static HeaderAbsensiModel header;
    public static JFrame parent;
    public AbsensiForm() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        loadTableTemp();
    }
    public void loadTableTemp()
    {
        List<Imodels> m = sqlLib.searchData4("Kelas", new String[]{"*"}, "where id='" + header.id_kelas + "'", KelasModel.class);
        this.jLabel1.setText("Absensi Kelas" + m.get(0).loadClass(new KelasModel()).name );
        //AbsensiTableModel.rowsType = new Object[] {JComboBox.class};
        //AbsensiTableModel table = new AbsensiTableModel();
        System.out.println("PRE-LD");
        List<Imodels> mod = sqlLib.searchProcedure(String.format("Call getAbsenView('%s');", header.id_kelas), AbsenView.class);
        System.out.println("LD");
        //this.jTable1.setModel(utilLib.loadTable(mod));
        DefaultTableModel table = (DefaultTableModel)this.jTable1.getModel();
        table.addColumn("nim");
        table.addColumn("name");
        table.addColumn("status");
        String[] items = new String[]{"Hadir","Tidak Hadir","Sakit","Izin"};
        JComboBox box = new JComboBox();
        box.addItem("Hadir");
        box.addItem("Tidak Hadir");
        box.addItem("Sakit");
        box.addItem("Izin");
//        box.setSelectedItem("Hadir");
//        box.setName("box");
        box.setSelectedIndex(0);
        jTable1.getColumnModel().getColumn(this.jTable1.getColumnCount()-1).setCellEditor(new javax.swing.DefaultCellEditor(box));
         jTable1.getColumnModel().getColumn(this.jTable1.getColumnCount()-1).setCellRenderer(new AbsensiTableRenderer(items));
//        List<List<Object>> data = new ArrayList();
        for (int i=0;i<mod.size();i++)
        {
            List<Object> obj = new ArrayList();
            for (int j=0;j<mod.get(i).loadAllNames().length;j++)
            {
                obj.add(mod.get(i).loadValues( mod.get(i).loadAllNames()[j]));
            }
//            box = new JComboBox();
 //           box.addItem("Hadir");
  //          box.addItem("Tidak Hadir");
    //        box.addItem("Sakit");
      //      box.addItem("Izin");
//            box.setName("box" + i);
//            obj.add(box);
            table.addRow(obj.toArray());
            table.setValueAt("Hadir", i, table.getColumnCount()-1);
        }
        if (table.getRowCount() > 0)
        {
            jTable1.setRowSelectionInterval(0, 0);
        }
        //jTable1.setModel(table);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Absensi Header");

        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConfirmUser.user = user;
        ConfirmUser.header = header.loadClass(new HeaderAbsensiModel());
        System.out.println("HEADER: " + ConfirmUser.header.id);
        List<DetailAbsensiModel> details = new ArrayList(); 
        List<Dictionary> tableValues = this.getValueFromTable();
        for (int i=0;i<tableValues.size();i++)
        {    
            details.add(new DetailAbsensiModel().loadModels(tableValues.get(i)).loadClass(new DetailAbsensiModel()));
        }
        ConfirmUser.details = details;
        ConfirmUser.parent = parent;
        ConfirmUser.parent2 = this;
        ConfirmUser confirm  = new ConfirmUser();
        confirm.setVisible(true);
        this.dispose();
//        JOptionPane.showMessageDialog(this,this.getValueFromTable()[0][jTable1.getColumnCount()-1], "TEST",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public List<Dictionary> getValueFromTable()
    {
        DefaultTableModel table = (DefaultTableModel)this.jTable1.getModel();
        //Object[][] values = new Object[table.getRowCount()][table.getColumnCount()];
        List<Dictionary> list = new ArrayList();
        
        for (int i=0;i<table.getRowCount();i++)
        {
            Dictionary dict = new Hashtable();
            for (int j=0;j<table.getColumnCount();j++)
            {
                System.out.println("CLASS: " + jTable1.getColumnClass(j).getName());
                Object obj = table.getValueAt(i, j);
                if (jTable1.getColumnName(j).equals("status"))
                {
                    try
                    {
                    obj = ((JComboBox)table.getValueAt(i, j)).getSelectedItem();
                    }
                    catch(Exception ex)
                    {
                        obj = obj;
                    }
                }
                System.out.println(table.getColumnName(j).getClass());
                dict.put(table.getColumnName(j),obj);
            }
            list.add(dict);
        }
        return list;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsensiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsensiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsensiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsensiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
