/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NullProgrammers_08;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import NullProgrammers_08.Libs.sqlLib;
import NullProgrammers_08.Libs.utilLib;
import NullProgrammers_08.Models.Imodels;
import NullProgrammers_08.Models.JurusanModel;
import NullProgrammers_08.Models.KelasModel;
import NullProgrammers_08.Models.ProdiModel;
import NullProgrammers_08.Models.ReportHeaderView;
import NullProgrammers_08.Models.ReportView;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DRONE003
 */
public class ReportForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        this.generateCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Dosen", "tanggal", "kelas", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jButton1.setText("Search Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton1)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String[] colnames= new String[]{"h.id","u.name as dosen","h.absendate as tanggal","k.name as kelas","h.total_mahasiswa as total"};
//        List<Imodels> results = sqlLib.searchData4("absensiHeader",colnames , String.format(" h inner join kelas k on k.id=h.id_kelas inner join users u on u.nik=h.Dosen inner join prodi p on k.id_prodi=p.id inner join jurusan j on j.id=p.id_jurusan where k.name='%s' and p.name='%s' and j.name='%s' and h.absenDate like '%s",this.jComboBox3.getSelectedItem(),this.jComboBox2.getSelectedItem(),this.jComboBox1.getSelectedItem(),this.jFormattedTextField1.getText()) + "%'", ReportHeaderView.class);
        System.out.println("call getReportHeader('" + this.jComboBox3.getSelectedItem() + "','" + this.jComboBox2.getSelectedItem() + "','" + this.jComboBox1.getSelectedItem() + "','" + this.jFormattedTextField1.getText()  + "%');");
        switch (jButton1.getText())
        {
            case "Search Report":
                getReportHeader();
                break;
            case "Generate Report":
                getReport();
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void getReportHeader()
    {
        List<Imodels> results = sqlLib.searchProcedure("call getReportHeader('" + this.jComboBox3.getSelectedItem() + "','" + this.jComboBox2.getSelectedItem() + "','" + this.jComboBox1.getSelectedItem() + "','" + this.jFormattedTextField1.getText()  + "%');",ReportHeaderView.class );
        DefaultTableModel table = utilLib.loadTable(results);
        jTable1.setModel(table);
        this.jButton1.setText("Generate Report");
    }
    public void getReport()
    {
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String id=  table.getValueAt(jTable1.getSelectedRow(),0).toString();
        List<Imodels> list = sqlLib.searchProcedure("call getReport('" + id + "');", ReportView.class);
        DefaultTableModel newTable = utilLib.loadTable(list);
        jTable1.setModel(newTable);
        this.jButton1.setText("Search Report");

    }
    public void generateCombobox()
    {
        this.jComboBox1.removeAllItems();
        this.jComboBox2.removeAllItems();
        this.jComboBox3.removeAllItems();
        this.jComboBox1.addItem("Jurusan");
        this.jComboBox2.addItem("Prodi");
        this.jComboBox3.addItem("Kelas");
        List<Imodels> mod = sqlLib.searchData4("Jurusan", new String[]{"*"}, "", JurusanModel.class);
        for (Imodels m : mod)
        {
            this.jComboBox1.addItem(m.loadValues("name").toString());
        }
        this.jComboBox1.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                List<Imodels> models = sqlLib.searchData4("prodi", new String[]{"*"}, " inner join jurusan on jurusan.id=prodi.id_jurusan where jurusan.name='" + e.getItem().toString() + "'", ProdiModel.class);
                jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                for (Imodels model : models)
                {
                    jComboBox2.addItem(model.loadValues("name").toString());
                }
            }            
        });
        this.jComboBox2.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                List<Imodels> models = sqlLib.searchData4("kelas", new String[]{"*"}, " inner join prodi on prodi.id=kelas.id_prodi where prodi.name='" + e.getItem().toString() + "'", KelasModel.class);
                jComboBox3.removeAllItems();
                for (Imodels model : models)
                {
                    jComboBox3.addItem(model.loadValues("name").toString());
                }
            }            
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
